name: Imperugo.HttpRequestLogger Build
on:
  push:
    branches:
      - main
    tags:
      - "*.*.*"
jobs:
  publish:
    name: Publish Nuget Packages
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Setup dotnet
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: |
            6.0.x
            7.0.x
            8.0.x

      - name: Show dotnet info
        run: dotnet --info

      - name: Unit Test
        run: dotnet test --verbosity quiet

      - name: Build main library
        run: dotnet pack ./src/Imperugo.HttpRequestLogger/Imperugo.HttpRequestLogger.csproj --version-suffix ${{ github.run_number }} -o ./packages/ -c Release

      - name: Build abstractions
        run: dotnet pack ./src/Imperugo.HttpRequestLogger.Abstractions/Imperugo.HttpRequestLogger.Abstractions.csproj --version-suffix ${{ github.run_number }} -o ./packages/ -c Release

      - name: Build mongo db provider
        run: dotnet pack ./src/Imperugo.HttpRequestLogger.MongoDb/Imperugo.HttpRequestLogger.MongoDb.csproj --version-suffix ${{ github.run_number }} -o ./packages/ -c Release

      - name: Publish nuget
        run: |
          for f in ./packages/*.nupkg
          do
            dotnet nuget push $f --api-key ${{ secrets.NuGetApiKey}} --source https://api.nuget.org/v3/index.json
          done
        shell: bash
